### ISSUE TITLE
Remove feedback form

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/artmuseum#2]
![image](https://user-images.githubusercontent.com/7841556/48355571-0270c900-e69d-11e8-8284-7646ca9bc190.png)

**Comment by codepixar** [comment]
@cristianraiber  - Removed feedback form. Please check.

![image](https://user-images.githubusercontent.com/43398174/48396083-736abc00-e743-11e8-8796-d3a1c35b5230.png)
