### ISSUE TITLE
Slider is broken in Elementor/front-end

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/artmuseum#3]
![image](https://user-images.githubusercontent.com/7841556/48356363-c2aae100-e69e-11e8-8859-b69ca47bcb62.png)

**Comment by codepixar** [comment]
@cristianraiber - Solved this issue. Please check.

![image](https://user-images.githubusercontent.com/43398174/48396171-c2b0ec80-e743-11e8-830e-d456ee54a370.png)

**Comment by cristianraiber** [comment]
![image](https://user-images.githubusercontent.com/7841556/48475073-a9bc4000-e804-11e8-8db6-a3e0fa33e198.png)

**Comment by cristianraiber** [comment]
@codepixar - default should be: no-repeat & cover for background. Otherwise it looks like this on resolutions bigger than 1080p.

**Comment by codepixar** [comment]
@cristianraiber  - I have change banner element settings no-repeat & cover for background and update demo data. Please check.
